README.md
docs/cisco.dcnm.dcnm_httpapi.rst

Summary of changes:
* Update doc links with relative links.
* Add link to CHANGELOG

Doc updates

---

plugins/action/dcnm_inventory.py
plugins/module_utils/network/dcnm/dcnm.py
plugins/modules/dcnm_inventory.py
tests/integration/targets/dcnm_inventory/tests/dcnm/merged.yaml
tests/integration/targets/dcnm_inventory/tests/dcnm/overridden.yaml
tests/integration/targets/dcnm_inventory/tests/dcnm/query.yaml

DCNM Inventory Code - Addressed 2 query enhancements
Added choices check

DCNM Inventory Code - Query enhancements, dcnm.py - choices check

---

plugins/modules/dcnm_network.py

DCNM_NETWORK - invalid params issue fix

DCNM_NETWORK - invalid params issue fix

---

plugins/modules/dcnm_network.py

DCNM Network TAG Modification Support Added

DCNM Network TAG Modification Support Added

---

plugins/modules/dcnm_vrf.py
tests/integration/targets/dcnm_vrf/tests/dcnm/deleted.yaml
tests/integration/targets/dcnm_vrf/tests/dcnm/merged.yaml
tests/integration/targets/dcnm_vrf/tests/dcnm/overridden.yaml
tests/integration/targets/dcnm_vrf/tests/dcnm/query.yaml
tests/integration/targets/dcnm_vrf/tests/dcnm/replaced.yaml
tests/unit/modules/dcnm/fixtures/dcnm_vrf.json
tests/unit/modules/dcnm/test_dcnm_vrf.py

DCNM PHASE2 - P1 - VRF_LITE EXTENSION MODULE - Initial Commit
This is the PR raised for the following development in VRF LITE Extension module,
dcnm_vrf.py/IT modules/UT modules.

DCNM PHASE2 - P1 - VRF_LITE EXTENSION MODULE - Initial Commit

---

plugins/modules/dcnm_inventory.py
tests/integration/targets/dcnm_inventory/tests/dcnm/deleted.yaml
tests/integration/targets/dcnm_inventory/tests/dcnm/merged.yaml
tests/integration/targets/dcnm_inventory/tests/dcnm/overridden.yaml
tests/integration/targets/dcnm_inventory/tests/dcnm/query.yaml
tests/unit/modules/dcnm/fixtures/dcnm_inventory.json

DCNM Inventory Code masking the device credentials as we have received a mail from devnet team.

DCNM Inventory Code masking the device credentials

---

plugins/modules/dcnm_template.py
tests/integration/targets/dcnm_template/tasks/dcnm.yaml
tests/integration/targets/prepare_dcnm_template/tasks/main.yaml

This PR contains following changes:
1. Update to build content with variable arguments
2. Update to handle initial setup and teardown of all required information during IT

Fix to template module to handle template with args

---

galaxy.yml

Update galaxy.yml release version

---

plugins/modules/dcnm_inventory.py

This PR fixes fixes the issue in setting the role of switch in #63

Fix for setting role of switch

---

plugins/modules/dcnm_vrf.py

This PR fixes the issue in setting neighbor_asn for vrflite in #66

Fix for neighbor_asn in vrflite

---

plugins/modules/dcnm_vrf.py

This PR fixes the issue in setting auto deploy for vrflite in #65

Fix for auto deploy flag in vrflite

---

plugins/action/dcnm_interface.py
plugins/action/dcnm_inventory.py
plugins/action/dcnm_vrf.py
plugins/httpapi/dcnm.py
plugins/module_utils/network/dcnm/dcnm.py
plugins/modules/dcnm_interface.py
plugins/modules/dcnm_network.py
plugins/modules/dcnm_policy.py
plugins/modules/dcnm_service_node.py
plugins/modules/dcnm_service_route_peering.py
plugins/modules/dcnm_template.py
plugins/modules/dcnm_vrf.py

Fix for flake8 warnings in galaxy

Fix for flake8 warnings

---

CHANGELOG.md
docs/cisco.dcnm.dcnm_network_module.rst
plugins/modules/dcnm_network.py
tests/integration/targets/dcnm_network/tests/dcnm/deleted.yaml
tests/integration/targets/dcnm_network/tests/dcnm/merged.yaml
tests/integration/targets/dcnm_network/tests/dcnm/overridden.yaml
tests/integration/targets/dcnm_network/tests/dcnm/query.yaml
tests/integration/targets/dcnm_network/tests/dcnm/replaced.yaml

Changes for DCNM network module enhancements. Support for following parameters are added to network module as part of this change
- Layer 2 Only
- Vlan Name
- Interface Description
- MTU for L3 interface
- ARP Suppression
- DHCPv4 Server 1/2/3
- DHCPv4 Server 1/2/3 VRF

Dcnm network enhancements

---

plugins/modules/dcnm_service_policy.py
plugins/modules/dcnm_service_route_peering.py

Fixed the following:
- handled the case of attach not being included in the config by user
- captured additional info for debugging

Fixed the attach not included case

---

plugins/module_utils/network/dcnm/dcnm.py

This PR refactors `dcnm_version_supported` to use actual version api's to query the running software version of DCNM.

Refactor dcnm_version_supported to use version apis

---

plugins/modules/dcnm_network.py
plugins/modules/dcnm_service_node.py
plugins/modules/dcnm_vrf.py
tests/integration/targets/dcnm_service_node/tasks/main.yaml
tests/integration/targets/dcnm_service_node/tests/dcnm/deleted.yaml
tests/integration/targets/dcnm_service_node/tests/dcnm/merged.yaml
tests/integration/targets/dcnm_service_node/tests/dcnm/overridden.yaml
tests/integration/targets/dcnm_service_node/tests/dcnm/query.yaml
tests/integration/targets/dcnm_service_node/tests/dcnm/replaced.yaml
tests/unit/modules/dcnm/test_dcnm_service_node.py

- DCNM 12 changes for service_node module
- Updates to network and vrf module

DCNM 12 changes for service_node module

---

plugins/modules/dcnm_network.py
plugins/modules/dcnm_vrf.py

Fixed the method to get VRF ID and NET ID

Fix the method to get VRF ID and NET ID

---

plugins/modules/dcnm_service_route_peering.py
tests/integration/targets/dcnm_service_route_peering/tasks/dcnm.yaml
tests/integration/targets/dcnm_service_route_peering/tests/dcnm/dcnm_service_route_peering_replace.yaml
tests/integration/targets/prepare_dcnm_service_route_peering/tasks/main.yaml
tests/unit/modules/dcnm/test_dcnm_service_route_peering.py

DCNM12 relted changes in SRP module

Service route peering module updated to support  DCNM12

---

plugins/modules/dcnm_network.py
plugins/modules/dcnm_vrf.py

Changes to support Vrf name alone to query vrf with config. 
Changes to Network name alone to query network with config.
Fixes the issue in #101.

Vrf name and network name for query with config

---

plugins/modules/dcnm_service_policy.py
tests/integration/targets/dcnm_service_policy/tasks/dcnm.yaml
tests/integration/targets/prepare_dcnm_service_policy/tasks/main.yaml
tests/unit/modules/dcnm/test_dcnm_service_policy.py

The Service Policy module has been updated to support DCNM12
A couple of additional fixes

Service Policy module changes to support DCNM12

---

plugins/modules/dcnm_policy.py
tests/unit/modules/dcnm/fixtures/dcnm_policy_payloads.json
tests/unit/modules/dcnm/test_dcnm_policy.py

Updated dcnm_policy module to perform retries to deploy policies.

policy module fix

---

plugins/modules/dcnm_template.py

Removed commented code in template module

Removed commented code in template module

---

plugins/httpapi/dcnm.py

This fixes a python string index error that was happening when invalid credentials were supplied for authenticating with DCNM/NDFC
The following displays behavior with this fix in place:
**Case1: Invalid credentials for DCNM:**
```shell
File "/var/folders/g4/zsm12cfd1rlg695d0mdxh2f40000gn/T/ansible_cisco.dcnm.dcnm_inventory_payload_e8wz629t/ansible_cisco.dcnm.dcnm_inventory_payload.zip/ansible/module_utils/connection.py", line 195, in __rpc__
ansible.module_utils.connection.ConnectionError: ["Error on attempt to connect and authenticate with DCNM controller: {'RETURN_CODE': 500, 'METHOD': 'POST', 'REQUEST_PATH': 'https://192.168.7.6:443/rest/logon', 'MESSAGE': 'Internal Server Error', 'DATA': 'Invalid JSON response: Invalid Credential'}", 'Error on attempt to connect and authenticate with …
```

Fix plugin invalid credential error handling 

---

plugins/httpapi/dcnm.py

Changes to support the latest NDFC login

Changes for latest NDFC login

---

plugins/modules/dcnm_template.py

Adding capability to create python type templates via new config option

Add Python template type support

---

docs/cisco.dcnm.dcnm_network_module.rst
plugins/modules/dcnm_network.py
tests/integration/targets/dcnm_network/tests/dcnm/self-contained-tests/sm_mcast_params.yaml
tests/integration/targets/dcnm_network/tests/dcnm/self-contained-tests/sm_mcast_update.yaml
tests/integration/targets/dcnm_network/tests/dcnm/self-contained-tests/so_mcast_update.yaml

Add support for NDFC network multicast group support

Add Mcast Group Address support for dcnm_network

---

docs/cisco.dcnm.dcnm_inventory_module.rst
plugins/modules/dcnm_inventory.py

DESCRIPTION::
Updates to inventory module documentation

Update inventory module documentation

---

CHANGELOG.md
README.md
docs/cisco.dcnm.dcnm_network_module.rst
docs/cisco.dcnm.dcnm_vrf_module.rst
galaxy.yml
plugins/modules/dcnm_network.py
plugins/modules/dcnm_vrf.py
tests/integration/targets/dcnm_network/tests/dcnm/query.yaml
tests/integration/targets/dcnm_network/tests/dcnm/replaced.yaml
tests/integration/targets/dcnm_network/tests/dcnm/self-contained-tests/deleted_net_all.yaml
tests/integration/targets/dcnm_network/tests/dcnm/self-contained-tests/merged_net_all.yaml
tests/integration/targets/dcnm_network/tests/dcnm/self-contained-tests/overridden_net_all.yaml
tests/integration/targets/dcnm_network/tests/dcnm/self-contained-tests/replaced_net_all.yaml
tests/integration/targets/dcnm_network/tests/dcnm/self-contained-tests/scale.yaml
tests/integration/targets/dcnm_vrf/tests/dcnm/deleted.yaml
tests/integration/targets/dcnm_vrf/tests/dcnm/merged.yaml
tests/integration/targets/dcnm_vrf/tests/dcnm/overridden.yaml
tests/integration/targets/dcnm_vrf/tests/dcnm/query.yaml
tests/integration/targets/dcnm_vrf/tests/dcnm/replaced.yaml
tests/integration/targets/dcnm_vrf/tests/dcnm/self-contained-tests/deleted_vrf_all.yaml
tests/integration/targets/dcnm_vrf/tests/dcnm/self-contained-tests/merged_vrf_all.yaml
tests/integration/targets/dcnm_vrf/tests/dcnm/self-contained-tests/overridden_vrf_all.yaml
tests/integration/targets/dcnm_vrf/tests/dcnm/self-contained-tests/replaced_vrf_all.yaml
tests/integration/targets/dcnm_vrf/tests/dcnm/self-contained-tests/scale.yaml
tests/unit/modules/dcnm/fixtures/dcnm_network.json
tests/unit/modules/dcnm/fixtures/dcnm_vrf.json
tests/unit/modules/dcnm/test_dcnm_network.py
tests/unit/modules/dcnm/test_dcnm_vrf.py

Release 3.1.0

---

CHANGELOG.md
README.md
galaxy.yml

This is a double commit of the following fixes
https://github.com/CiscoDevNet/ansible-dcnm/pull/213

Double commit 311 fixes

---

plugins/modules/dcnm_policy.py
tests/integration/targets/dcnm_policy/tests/dcnm/dcnm_policy_merge.yaml
tests/unit/modules/dcnm/fixtures/dcnm_policy_configs.json
tests/unit/modules/dcnm/fixtures/dcnm_policy_payloads.json
tests/unit/modules/dcnm/test_dcnm_policy.py

This commit fixes the following issue (#202) in dcnm_policy module:
Policies specified under the switch block of playbook are not processed as expected. This update fixes this issue.

Fix to properly process policies under switch block - issue #202

---

docs/cisco.dcnm.dcnm_vrf_module.rst
plugins/action/dcnm_vrf.py
plugins/modules/dcnm_inventory.py
plugins/modules/dcnm_links.py
plugins/modules/dcnm_network.py
plugins/modules/dcnm_resource_manager.py
plugins/modules/dcnm_rest.py
plugins/modules/dcnm_vrf.py
tests/integration/targets/dcnm_vrf/tests/dcnm/deleted.yaml
tests/integration/targets/dcnm_vrf/tests/dcnm/merged.yaml
tests/integration/targets/dcnm_vrf/tests/dcnm/overridden.yaml
tests/integration/targets/dcnm_vrf/tests/dcnm/query.yaml
tests/integration/targets/dcnm_vrf/tests/dcnm/replaced.yaml
tests/integration/targets/dcnm_vrf/tests/dcnm/self-contained-tests/vrf_lite.yaml
tests/unit/modules/dcnm/fixtures/dcnm_vrf.json
tests/unit/modules/dcnm/test_dcnm_vrf.py

- Added support to configure multiple vrf lite extensions
- Added idempotence support for vrf lite
- IT/UT cases for new support

Vrf lite enhancements

---

docs/cisco.dcnm.dcnm_vrf_module.rst
plugins/action/dcnm_vrf.py
plugins/modules/dcnm_vrf.py
tests/integration/targets/dcnm_vrf/tests/dcnm/deleted.yaml
tests/integration/targets/dcnm_vrf/tests/dcnm/merged.yaml
tests/integration/targets/dcnm_vrf/tests/dcnm/overridden.yaml
tests/integration/targets/dcnm_vrf/tests/dcnm/query.yaml
tests/integration/targets/dcnm_vrf/tests/dcnm/replaced.yaml
tests/integration/targets/dcnm_vrf/tests/dcnm/self-contained-tests/vrf_lite.yaml

- Made interface a required parameter for vrf lite configs
- Fix for malformed list issue.

vrf lite changes

---

docs/cisco.dcnm.dcnm_inventory_module.rst
galaxy.yml
plugins/modules/dcnm_inventory.py

* Support for new roles in Inventory module
* Removed the restriction for netcommon version supported

Support for new roles in Inventory module

---

CHANGELOG.md
README.md
docs/cisco.dcnm.dcnm_inventory_module.rst
docs/cisco.dcnm.dcnm_vrf_module.rst
galaxy.yml
plugins/action/dcnm_vrf.py
plugins/module_utils/network/dcnm/dcnm.py
plugins/modules/dcnm_inventory.py
plugins/modules/dcnm_links.py
plugins/modules/dcnm_network.py
plugins/modules/dcnm_resource_manager.py
plugins/modules/dcnm_rest.py
plugins/modules/dcnm_vrf.py
tests/integration/targets/dcnm_links/tests/dcnm/dcnm_links_misc.yaml
tests/integration/targets/dcnm_vrf/tests/dcnm/deleted.yaml
tests/integration/targets/dcnm_vrf/tests/dcnm/merged.yaml
tests/integration/targets/dcnm_vrf/tests/dcnm/overridden.yaml
tests/integration/targets/dcnm_vrf/tests/dcnm/query.yaml
tests/integration/targets/dcnm_vrf/tests/dcnm/replaced.yaml
tests/integration/targets/dcnm_vrf/tests/dcnm/self-contained-tests/vrf_lite.yaml
tests/unit/modules/dcnm/fixtures/dcnm_links_configs.json
tests/unit/modules/dcnm/fixtures/dcnm_links_payloads.json
tests/unit/modules/dcnm/fixtures/dcnm_vrf.json
tests/unit/modules/dcnm/test_dcnm_links.py
tests/unit/modules/dcnm/test_dcnm_vrf.py

Release 3.3.0

---

docs/cisco.dcnm.dcnm_network_module.rst
docs/cisco.dcnm.dcnm_vrf_module.rst
plugins/modules/dcnm_network.py
plugins/modules/dcnm_vrf.py
tests/integration/targets/dcnm_network/tests/dcnm/deleted.yaml
tests/integration/targets/dcnm_network/tests/dcnm/merged.yaml
tests/integration/targets/dcnm_network/tests/dcnm/overridden.yaml
tests/integration/targets/dcnm_network/tests/dcnm/query.yaml
tests/integration/targets/dcnm_network/tests/dcnm/replaced.yaml

These changes contains fix to network and vrf modules to manage deploy flag
Fixes issues in #230, #231 and #232 
Related changes to IT cases

Fix to network and vrf modules to manage deploy flag

---

CHANGELOG.md
README.md
docs/cisco.dcnm.dcnm_network_module.rst
docs/cisco.dcnm.dcnm_vrf_module.rst
galaxy.yml
plugins/modules/dcnm_network.py
plugins/modules/dcnm_vrf.py
tests/integration/targets/dcnm_network/tests/dcnm/deleted.yaml
tests/integration/targets/dcnm_network/tests/dcnm/merged.yaml
tests/integration/targets/dcnm_network/tests/dcnm/overridden.yaml
tests/integration/targets/dcnm_network/tests/dcnm/query.yaml
tests/integration/targets/dcnm_network/tests/dcnm/replaced.yaml
tests/integration/targets/dcnm_network/tests/dcnm/self-contained-tests/ingress_replication_networks.yaml

Release 3.3.1

---

docs/cisco.dcnm.dcnm_inventory_module.rst
plugins/modules/dcnm_inventory.py

add save and deploy options to dcnm_inventory module

---

README.md
docs/cisco.dcnm.dcnm_httpapi.rst
plugins/httpapi/dcnm.py

add login domain support for httpapi plugin

---

docs/cisco.dcnm.dcnm_vrf_module.rst
plugins/modules/dcnm_vrf.py
tests/unit/modules/dcnm/fixtures/dcnm_vrf.json

add import_evpn_rt and export_evpn_rt to the attach

---

plugins/modules/dcnm_links.py

changes in this PR:
- Fix an issue when using merge to update mpls_underlay links
- Fix a typo in the code that causes peer1_description and peer2_description are not updated correctly

fix an issue when using merge to update mpls_underlay link

---

.github/workflows/main.yml

Fix for netcommon install issue in Git action CI pipeline.

Fix for netcommon install issue in Git action

---

docs/cisco.dcnm.dcnm_network_module.rst
plugins/modules/dcnm_network.py
tests/integration/targets/dcnm_network/tests/dcnm/self-contained-tests/tor_ports_networks.yaml
tests/unit/modules/dcnm/fixtures/dcnm_network.json
tests/unit/modules/dcnm/test_dcnm_network.py

Support for attach network to ports of paired TOR switch

Support for attach network to ports of paired TOR switch

---

.github/workflows/main.yml
CHANGELOG.rst
README.md
docs/cisco.dcnm.dcnm_network_module.rst
galaxy.yml
plugins/modules/dcnm_network.py
tests/integration/targets/dcnm_network/tests/dcnm/self-contained-tests/tor_ports_networks.yaml
tests/unit/modules/dcnm/fixtures/dcnm_network.json
tests/unit/modules/dcnm/test_dcnm_network.py

Release  3.4.3

---

tests/integration/targets/dcnm_policy/tests/dcnm/dcnm_policy_delete.yaml
tests/integration/targets/dcnm_policy/tests/dcnm/dcnm_policy_merge.yaml
tests/integration/targets/dcnm_policy/tests/dcnm/dcnm_policy_merge_multi_switch.yaml
tests/integration/targets/dcnm_policy/tests/dcnm/dcnm_policy_modify.yaml
tests/integration/targets/dcnm_policy/tests/dcnm/dcnm_policy_query.yaml
tests/integration/targets/dcnm_policy/tests/dcnm/dcnm_policy_with_vars_merge.yaml

Fix assert for policy create response in IT

Fix assert for policy create response in IT

---

plugins/modules/dcnm_interface.py
tests/integration/targets/prepare_dcnm_intf/tasks/main.yaml
tests/unit/modules/dcnm/fixtures/dcnm_intf_bunched_configs.json
tests/unit/modules/dcnm/fixtures/dcnm_intf_eth_configs.json
tests/unit/modules/dcnm/fixtures/dcnm_intf_mixed_configs.json
tests/unit/modules/dcnm/fixtures/dcnm_intf_multi_configs.json
tests/unit/modules/dcnm/fixtures/dcnm_intf_multi_intf_configs.json
tests/unit/modules/dcnm/test_dcnm_intf.py

This commit includes the fixes for issues #276 and #278
Speed parameter was not processed in the current implementation and thus idempotence test cases w,r,t speed failed.
Code is now updated to process speed parameter and update accordingly.
This commit also includes updates to accept speed parameter through playbook in a case insensitive way. Code is now updated to handle these cases.

Fix for interface module, Issues 276 and 278

---

plugins/modules/dcnm_inventory.py

Inventory module crashed if the switch IP specified is not available. Fixed it with a valid error.

Enhanced error reporting for non available inventory IP

---

README.md
docs/cisco.dcnm.dcnm_fabric_module.rst
plugins/module_utils/fabric/update.py
plugins/modules/dcnm_fabric.py
tests/integration/targets/dcnm_fabric/tests/dcnm_fabric_deleted_basic.yaml
tests/integration/targets/dcnm_fabric/tests/dcnm_fabric_merged_basic.yaml
tests/integration/targets/dcnm_fabric/tests/dcnm_fabric_merged_save_deploy.yaml
tests/integration/targets/dcnm_fabric/tests/dcnm_fabric_replaced_basic.yaml
tests/integration/targets/dcnm_fabric/tests/dcnm_fabric_replaced_save_deploy.yaml

This PR addresses a couple issues found after merge with develop branch, adds documentation, and addresses review comments from the initial dcnm_fabric commit.  Details below.
1. DEPLOY key was not removed from commit payload in some cases.
2. query and deleted states, were expecting lower-case fabric_name instead of upper-case FABRIC_NAME.
3. Per review comments, changed logging such that it is enabled via ENV variable NDFC_LOGGING_CONFIG.
4. Other review comments addressed (copyright date fix, version added fix)
5. Added module documentation.

dcnm_fabric: documentation and fixes (ready for review)

---

CHANGELOG.rst
docs/cisco.dcnm.dcnm_image_upload_module.rst
docs/cisco.dcnm.dcnm_vpc_pair_module.rst
galaxy.yml
plugins/modules/dcnm_image_upload.py
plugins/modules/dcnm_vpc_pair.py

Documentation and Copyright changes

Documentation changes

---

docs/cisco.dcnm.dcnm_inventory_module.rst
plugins/modules/dcnm_inventory.py

Resolves #128 
I tested this locally and can provide logs if needed, but as the issue states, only the ip param is required in the config list.

Resolve Issue #128

---

plugins/modules/dcnm_network.py
tests/integration/targets/dcnm_network/tasks/main.yaml

Fix for network_crash during query. 
Fix for #314

Fix for network_crash during query

---

plugins/modules/dcnm_network.py

**Summary:**
This fixes two problems:
* There is a problem after creating a network when the `deploy` flag is set to `false`.  The first time the network will be created and remain in `pending` state in NDFC but the second time the playbook is run the network will be deployed even though the flag is still set to `false`.
**Sample Playbook:**
```yaml
- name: Manage Networks
cisco.dcnm.dcnm_network:
fabric: nac-msd1
state: replaced
config:
- net_name: NaC-Net01
is_l2only: False
vrf_name: NaC-VRF01
net_id: 130001
vlan_id: 2301
vlan_name: NaC-Net01_vlan2301
gw_ip_subnet: 192.168.1.1/24
arp_suppress: False
int_desc: Configured by Ansible NetAsCode
mtu_l3intf: 9216
route_target_both: False
route_tag: 12345
attach:
- ip_address: 10.15.38.13
ports: ['Ethernet1/13', 'Ethernet1/14']
- ip_address: …
```

Prevent network deploy when user deploy flag is false #375

---

galaxy.yml

Update galaxy.yml to indicate develop branch is a DEV version of the code.
This adheres to semantic versioning (https://semver.org/)
* https://semver.org/#spec-item-9

Update galaxy.yml to indicate DEV version for develop branch

---

plugins/modules/dcnm_interface.py
plugins/modules/dcnm_inventory.py

* Resolves #486 
* And issue in nightly NaC run
```shell
TASK [cisco.nac_dc_vxlan.create : Manage Interface Trunk in Nexus Dashboard] **************************************************************************************************************************************
Tuesday 05 August 2025  17:24:32 -0400 (0:00:00.022)       0:11:29.062 ******** 
Tuesday 05 August 2025  17:24:32 -0400 (0:00:00.021)       0:11:29.061 ******** 
fatal: [nac-ibgp-fabric1]: FAILED! => {"changed": false, "module_stderr": "'CDP_ENABLE'", "module_stdout": "", "msg": "MODULE FAILURE: No start of json char found\nSee stdout/stderr for the exact error"}
```

dcnm_inventory: Fix set_role issue
