CiscoDevNet/ansible-dcnm

README.md
We have received several requests to add a sample hosts file for authenticating the connection to DCNM.  This PR adds a sample hosts file to the README in both INI and YAML formats to clarify how the httpapi dcnm plugin is used.
=> Add sample hosts file

plugins/modules/dcnm_template.py, tests/integration/targets/dcnm_policy/tasks/dcnm.yaml, tests/integration/targets/prepare_dcnm_policy/tasks/main.yaml
Changes in this commit
- Updated response handling in Template module to process responses for templates with and without args
- Policy It cases require a template with args. It is now created in prepare_dcnm_policy
- Cleanup of all the templates and policies created during init
=> Template and Policy modules fixes after moving to 11.5 DCNM

.github/workflows/main.yml, playbooks/roles/dcnm_fabric/dcnm_hosts.yaml, playbooks/roles/dcnm_fabric/dcnm_tests.yaml, plugins/modules/dcnm_vrf.py, tests/integration/targets/dcnm_fabric/defaults/main.yaml, tests/integration/targets/dcnm_fabric/meta/main.yaml, tests/integration/targets/dcnm_fabric/tasks/dcnm.yaml, tests/integration/targets/dcnm_fabric/tasks/fabric_setup.yaml, tests/integration/targets/dcnm_fabric/tasks/main.yaml, tests/integration/targets/dcnm_fabric/tests/exec_vars/vrfs.yaml, tests/integration/targets/dcnm_fabric/tests/spine_leaf_basic.yaml, tests/integration/targets/dcnm_fabric/tests/spine_leaf_merged.yaml, tests/integration/targets/dcnm_fabric/tests/spine_leaf_overridden.yaml, tests/integration/targets/dcnm_fabric/tests/spine_leaf_replaced.yaml, tests/integration/targets/dcnm_fabric/tests/spine_leaf_replaced_2.yaml
Summary of updates:
* Add new gihub actions CI file to build collection, run unit tests and generate simple code coverage report.
* Add new dcnm_fabric role tests to validate modules using a full fabric
* Additional coverage will be added to these tests.  This is only a starting point.
* More tests to be added once dcnm_vrf and dcnm_network query capabilities added to query based on object key
* Fixes the following bugs with dcnm_vrf module
* Type conversion for vrf config data when read from an ansible file
* VRFs were deployed even when the deploy flag was set to false
* Removed source parameter from examples and hardcoded it to None.  This should not be exposed in the playbook parameters but leaving it here just in case customers have specified it in their playbooks.
* Whitespace …
=> Add full fabric integration tests and github actions ci tasks

plugins/modules/dcnm_vrf.py
Fixed the dcnm vrf - query filter based on vrf name/vrf id and vlan.
vrf name is mandatory in config and rest are options.
=> DCNM VRF - Query filter fixed

requirements.txt
Our httpapi plugin uses the `requests` python module so we need to include it in our `requirements.txt` file
=> Add python requests module

plugins/module_utils/network/dcnm/dcnm.py, plugins/modules/dcnm_inventory.py
This fixes a bug where the `no_log` parameter was not being honored if set in the parameter spec.
There are two updates here:
* Update to module utils to allow a module write to set the `no_log` option and pass the Ansible module to add the parameter to the object no_log parameters
* Modify `dcnm_inventory` to not log authentication credentials when adding devices to the inventory
The new output in the ansible logs will be as follows
```json
{
"auth_proto": "MD5",
"max_hops": 0,
"password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
"preserve_config": false,
"role": "leaf",
"seed_ip": "n9kv-leaf4",
"user_name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
}
```
**Note:** We can update all of the modules to pass the ansible module object so it's no longer an optional parameter but this was the least …
=> Honor no_log parameters

plugins/httpapi/dcnm.py
This fixes https://github.com/CiscoDevNet/ansible-dcnm/issues/46 to add a check to our httpapi plugin to verify the DCNM controller URL is reachable from the Ansible controller and generates a meaningful error message if not.
With this change the following error message is generated
```bash
ansible.module_utils.connection.ConnectionError: HTTPSConnectionPool(host='192.168.1.1', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10603a3a0>: Failed to establish a new connection: [Errno 60] Operation timed out'))
Please verify that the DCNM controller HTTPS URL (https://192.168.1.1:443) is
reachable from the Ansible controller and try again
fatal: [192.168.1.1]: FAILED! => {
"changed": false,
"module_stderr": …
```
=> Provide meaningful error when DCNM controller not accessible

docs/cisco.dcnm.dcnm_policy_module.rst, docs/cisco.dcnm.dcnm_template_module.rst, plugins/modules/dcnm_policy.py, plugins/modules/dcnm_template.py, tests/integration/targets/dcnm_policy/tests/dcnm/dcnm_policy_delete.yaml, tests/integration/targets/dcnm_policy/tests/dcnm/dcnm_policy_merge.yaml, tests/integration/targets/dcnm_policy/tests/dcnm/dcnm_policy_merge_checkmode.yaml, tests/integration/targets/dcnm_policy/tests/dcnm/dcnm_policy_merge_multi_switch.yaml, tests/integration/targets/dcnm_policy/tests/dcnm/dcnm_policy_modify.yaml, tests/integration/targets/dcnm_policy/tests/dcnm/dcnm_policy_query.yaml, tests/integration/targets/dcnm_policy/tests/dcnm/dcnm_policy_with_vars_merge.yaml, tests/integration/targets/dcnm_template/tests/dcnm/dcnm_template_merge.yaml, tests/unit/modules/dcnm/test_dcnm_template.py
This PR fixes the following:
* Fixes documentation to display the `deploy:` parameter must be indented to match the `config:` parameter
* Re-orders `state:` and `deploy:` parameters in the integration tests to be above `config:` but at the same indent level
* Fixes trailing white space issues in template and policy tests
* Removes a few unused import statements
* Fixes a few issues with `dcnm_template`
* If the `config:` parameter is not specified or is empty the module generates a traceback.
* Adds a check in `dcnm_template_validate_input` function to check for return code greater then 400 return the failure as a json fail message instead of silently ignoring the failure
* Fixes one of the unit tests to test for the json failure for error return code
* Fixes associated integration test …
=> [WIP] dcnm_policy deploy flag issue

plugins/modules/dcnm_template.py, tests/integration/targets/prepare_dcnm_template/tasks/main.yaml, tests/unit/modules/dcnm/test_dcnm_template.py
This PR fixes the following:
1. The format of the CLI commands sent to DCNM server was wrong since all blank spaces were stripped. This is now fixed
2. Some cleanup of templates during prepare test cases
3. Open log files only when logs are used and not open it by default
=> Template format fix

plugins/module_utils/network/dcnm/dcnm.py, plugins/modules/dcnm_network.py
This PR adds the capability to specify vrf_name as "" for L2 networks. For L2 networks, user can either specify vrf_name as "" or they can avoid specifying vrf_name at all
=> Vrf name input change for L2 networks

plugins/modules/dcnm_network.py, plugins/modules/dcnm_vrf.py
- The method used to query the available vrf/net id should be 'GET' in DCNM 12 and 'POST' for DCNM 11. Fixed it.
- There was a infinite loop happening in a while statement, fixed it in vrf and network.
- The URL used to get net id in network module for DCNM version 11 was wrong. Corrected it.
=> Fix to correct the methods to get vrf/net id during configuration

plugins/modules/dcnm_inventory.py
This fixes an issue where the dcnm_inventory module was not working properly with ndfc.
We need to call the `dcnm_version_supported` api first so that the connection gets established before calling `get_fabric_details` so that it does not result in empty output.
=> Fix dcnm_inventory version check

plugins/modules/dcnm_service_route_peering.py, tests/unit/modules/dcnm/test_dcnm_intf.py
There was an extra timeout that was leftout during previous cleanup which is now removed from service route peering code
Cleaned up Interface Ut code to not create a UT log file if a specific log_msg has not been called.
=> Removed unwanted timeout and UT log file creation

docs/cisco.dcnm.dcnm_network_module.rst, plugins/module_utils/network/dcnm/dcnm.py, plugins/modules/dcnm_network.py, tests/integration/targets/dcnm_network/tasks/dcnm.yaml, tests/integration/targets/dcnm_network/tasks/main.yaml, tests/integration/targets/dcnm_network/tests/dcnm/self-contained-tests/sm_dhcp_params.yaml, tests/integration/targets/dcnm_network/tests/dcnm/self-contained-tests/sm_dhcp_update.yaml, tests/integration/targets/dcnm_network/tests/dcnm/self-contained-tests/so_dhcp_update.yaml, tests/unit/modules/dcnm/fixtures/dcnm_intf_subint_configs.json
This is a cherry-pick of the recent feature support I added and published as a hot-fix to Ansible Galaxy.  We don't have this feature in develop so this is essentially a double commit.
Original commit here: https://github.com/CiscoDevNet/ansible-dcnm/commit/a7de8a969bb00bac2af2843f6e6add87997e51fc
There are also a couple of formatting changes that my IDE picked up and changed.
=> Add dhcp_loopback_id parameter support

plugins/modules/dcnm_policy.py, tests/integration/targets/dcnm_policy/tests/dcnm/dcnm_policy_modify.yaml, tests/unit/modules/dcnm/fixtures/dcnm_policy_configs.json, tests/unit/modules/dcnm/test_dcnm_policy.py
ISSUE: https://github.com/CiscoDevNet/ansible-dcnm/issues/139
DESCRIPTION:
When an existing  policy is updated with policy ID, the description filed is being set to empty.
FIX:
- "description" field is appropriately updated during update policy
- Another issue that is fixed in this PR is allowing additional policy create using an existing policy ID
- Added UT and IT cases for the same
=> Fix for issue 139 - description is empty during update with polict ID

plugins/modules/dcnm_interface.py, tests/integration/targets/dcnm_interface/tests/dcnm/dcnm_intf_multi_intf_merge.yaml, tests/unit/modules/dcnm/fixtures/dcnm_intf_multi_intf_configs.json, tests/unit/modules/dcnm/fixtures/dcnm_intf_multi_intf_payloads.json, tests/unit/modules/dcnm/test_dcnm_intf.py
ISSUE: #137
DESCRIPTION:
During merge operation for an existing interface, aggregate objects like member interfaces, freeform config etc are being replaced. This issue was raised to change this behaviour.
FIX:
This code change will enable merge of aggregate objects instead of replacing them during merge. This is only applicable to aggregate objects (lists) and behaviour in the case of all other objects remains the same
=> Fix for issue 137 - merge aggregate objects instead of replacing them for merge state operation

plugins/modules/dcnm_network.py
Fixes the issue in #143
DESCRIPTION:
DCNM network attach of orphan ports in vpc paired switches using network module does not work.
FIX:
- While attaching vpc paired switches,  need to attach both the switches.
- While generating the RESTAPI payload for attach for vpc paired switches, an entry should be there for both the switches.
=> Fix for DCNM network attach in vpc paired switches

docs/cisco.dcnm.dcnm_policy_module.rst, plugins/modules/dcnm_policy.py, tests/integration/targets/dcnm_policy/tests/dcnm/dcnm_policy_delete.yaml, tests/integration/targets/dcnm_policy/tests/dcnm/dcnm_policy_merge.yaml, tests/integration/targets/dcnm_policy/tests/dcnm/dcnm_policy_merge_multi_switch.yaml, tests/integration/targets/dcnm_policy/tests/dcnm/dcnm_policy_merge_same_template.yaml, tests/integration/targets/dcnm_policy/tests/dcnm/dcnm_policy_modify.yaml, tests/integration/targets/dcnm_policy/tests/dcnm/dcnm_policy_query.yaml, tests/integration/targets/dcnm_policy/tests/dcnm/dcnm_policy_with_vars_merge.yaml, tests/integration/targets/prepare_dcnm_policy/tasks/main.yaml, tests/unit/modules/dcnm/fixtures/dcnm_policy_payloads.json, tests/unit/modules/dcnm/test_dcnm_policy.py
In the DCNM module there is no option to push individual policy changes during DELETE operations. In the current implementation, a Fabric level config deploy is executed after DELETE of Policies. In large fabrics this may take considerable time (because of fabric level deploy) even if the DELETE operation is restricted to a few switches. 
To solve this problem, once a Policy is deleted, deploy operation is executed only for the specific switches which are impacted by the DELETE. This way the operation will be much quicker.
NOTE: Even if a single policy is deleted, a switch level deploy will deploy all the pending configuration with respect to the switch.
=> Switch level deploy instead of fabric level deploy for policy module

plugins/modules/dcnm_network.py
Fixes the issue in #169 
DESCRIPTION:
DCNM network module generates traceback on attaching switches to an existing network.
FIX:
- 'isLayer2Only' and 'suppressArp' are bool params, but were treated as string params. Fixed  it
=> Fix for network module traceback

galaxy.yml, plugins/httpapi/dcnm.py
Fixes issue in #168 
DESCRIPTION:
DCNM return 401 for various scenarios like fabric not present. Current send call to net common retries continuously to login whenever 401 error is returned for a send request, and this happens until session timeout is reached.
FIX:
- Added retry count to send API, now send ill error out once the retry limit is reached. 
- Bumped min required netcommon(send API supports retry count from netcommon version 2.6.1 onwards)
=> Changes to add retry limit to send API on 401 return code scenarios

galaxy.yml
Change Reason:
If you want to display a license on your collection page in Automation Hub, you will need to use the `license` key in your galaxy.yml file, not the `license_file` key
=> Update galaxy file license key

plugins/modules/dcnm_network.py, tests/integration/targets/dcnm_network/tests/dcnm/self-contained-tests/sm_mcast_update.yaml
This update removes the default value for the `multicast_group_address` property.  There are several issues that occur when we set a default value for this property:
* An error is generated for unicast only fabrics (Where the ingress-replication) setting is being used instead of mcast.
* The default value is set by the fabric creator in the fabric template so it does not make sense to pick one for the module.
Addresses issue: https://github.com/CiscoDevNet/ansible-dcnm/issues/185
Validation:
* Tested against dcnm 11.5
* Tested against ndfc 2.2(1h)
* Added idempotence tests for default and non-defaut mcast values
=> Fix for mcast unicast issue

plugins/modules/dcnm_policy.py, tests/integration/targets/dcnm_policy/tests/dcnm/dcnm_policy_delete.yaml
This PR includes code changes in
- Policy module to check for deploy flag even during delete operations
- IT test cases to check for delete without and with deploy flag being set
=> Fix in dcnm_policy module to consider deploy flag during DELETE operations

CHANGELOG.md, README.md, galaxy.yml
This is a hotfix to restrict installs of netcommon to versions `>=2.6.1,<=4.1.0` due to issue: https://github.com/CiscoDevNet/ansible-dcnm/issues/209
=> Release 3.1.1

plugins/modules/dcnm_inventory.py
This commit fixes the config-save issue when there are only pre-provision switches in playbook along with only pre-provision switches in fabric.
=> Fix for config-save with pre-provision switches only

plugins/module_utils/network/dcnm/dcnm.py, plugins/modules/dcnm_links.py, tests/integration/targets/dcnm_links/tests/dcnm/dcnm_links_misc.yaml, tests/unit/modules/dcnm/fixtures/dcnm_links_configs.json, tests/unit/modules/dcnm/fixtures/dcnm_links_payloads.json, tests/unit/modules/dcnm/test_dcnm_links.py
This commit includes changes to dcnm_links module to:
- identify all switches which are in monitoring state
- identify all switches which are managable
- check for monitoring and managable attributes before deploy
- avoid deploying on fabrics which are in monitoring state
- avoid deploy to switches which have managable set to false
Added IT and UT cases to verify the above scenarios.
Updated the dcnm.py module to add logicalName to Serial Number mappings to inventory_data in case ipAddress is "". This will be the case for META switches.
=> Added checks for fabric monitoring status and switch's managable attributes during deploy

plugins/modules/dcnm_network.py, tests/integration/targets/dcnm_network/tests/dcnm/self-contained-tests/ingress_replication_networks.yaml
The default multicast group address should be "" in case of networks creates in fabrics with ingress replication enabled.
=> Fix default mcast group address in network module

docs/cisco.dcnm.dcnm_interface_module.rst, plugins/modules/dcnm_interface.py, plugins/modules/dcnm_policy.py, tests/integration/targets/dcnm_interface/tasks/dcnm.yaml, tests/integration/targets/dcnm_interface/tests/dcnm/dcnm_delete_deploy.yaml, tests/integration/targets/dcnm_interface/tests/dcnm/dcnm_delete_diff_options.yaml, tests/integration/targets/dcnm_interface/tests/dcnm/dcnm_intf_misc.yaml, tests/integration/targets/prepare_dcnm_intf/tasks/main.yaml, tests/unit/modules/dcnm/fixtures/dcnm_intf_aa_fex_configs.json, tests/unit/modules/dcnm/fixtures/dcnm_intf_bunched_configs.json, tests/unit/modules/dcnm/fixtures/dcnm_intf_eth_configs.json, tests/unit/modules/dcnm/fixtures/dcnm_intf_have_all_payloads.json, tests/unit/modules/dcnm/fixtures/dcnm_intf_lo_configs.json, tests/unit/modules/dcnm/fixtures/dcnm_intf_mixed_configs.json, tests/unit/modules/dcnm/fixtures/dcnm_intf_multi_configs.json, tests/unit/modules/dcnm/fixtures/dcnm_intf_multi_intf_configs.json, tests/unit/modules/dcnm/fixtures/dcnm_intf_pc_configs.json, tests/unit/modules/dcnm/fixtures/dcnm_intf_query_configs.json, tests/unit/modules/dcnm/fixtures/dcnm_intf_st_fex_configs.json, tests/unit/modules/dcnm/fixtures/dcnm_intf_subint_configs.json, tests/unit/modules/dcnm/fixtures/dcnm_intf_svi_configs.json, tests/unit/modules/dcnm/fixtures/dcnm_intf_vpc_configs.json, tests/unit/modules/dcnm/test_dcnm_intf.py
This commit in dcnm_interface module includes the following updates:
- Check deploy flag during deleted and overridden states. If deploy is false, do not deploy deleted interfaces. Just mark them as deleted.
- Check if switches included in playbook are manageable. If not return error indicating the same
- Check if Fabric mode is read_only. If it is read_only return error without making any changes
=> Fix to check for deploy flag during delete operation

docs/cisco.dcnm.dcnm_inventory_module.rst, plugins/modules/dcnm_inventory.py, tests/unit/modules/dcnm/fixtures/dcnm_inventory.json, tests/unit/modules/dcnm/test_dcnm_inventory.py
This update adds two new parameters called `discovery_username` and `discovery_password` to the `dcnm_inventory` module that are option but used during POAP and RMA workflows.
There are certain usecases like using AAA for authentication where a separate set of credentials may be needed during the discovery phase
=> dcnm_inventory: Add discovery username and password parameters

plugins/modules/dcnm_interface.py, tests/integration/targets/dcnm_interface/tasks/dcnm.yaml, tests/integration/targets/prepare_dcnm_intf/tasks/main.yaml
This PR includes the following changes:
- Add tasks to create VPC switch pairing in prepare_dcnm_intf 
- Create a template and policy to enable VPC feature
- Cleanup the VPC pairing related information in the Final cleanup tasks
Without these changes, VPC pairing  must be manually created using the GUI since some IT cases involving VPC interfaces are dependent on this. With these changes the pairing task has been automated,
=> Added VPC switch pairing tasks using dcnm_rest in preparatory and cleanup portions of IT

docs/cisco.dcnm.dcnm_interface_module.rst, plugins/modules/dcnm_interface.py, tests/integration/targets/dcnm_interface/tests/dcnm/dcnm_lo_fabric.yaml, tests/integration/targets/dcnm_interface/tests/dcnm/dcnm_lo_mpls.yaml
Addresses the following issues:
* https://github.com/CiscoDevNet/ansible-dcnm/issues/245
* https://github.com/CiscoDevNet/ansible-dcnm/issues/246
* Add support for mpls based fabric loopback interfaces
=> Add support for fabric loopback interfaces

plugins/modules/dcnm_inventory.py, tests/integration/targets/dcnm_inventory/tests/dcnm/merged.yaml
When max is set to and non zero value, and if there are other switches in the network within that hops, the discovery api returns all the switches available with that hop. In such cases inventory module tries to configure all available switches apart from the configured one. The fix now restricts the configuration only to the configured switch.
=> Fix for non zero max hop config

plugins/action/dcnm_inventory.py, plugins/modules/dcnm_network.py, plugins/modules/dcnm_vrf.py, tests/integration/targets/dcnm_network/tests/dcnm/overridden.yaml, tests/integration/targets/dcnm_vrf/tasks/dcnm.yaml
When using the network and vrf modules for the services as code collection I noticed that we cannot call the dcnm_vrf and dcnm_network modules without the `config` parameter but the module does support this to remove all VRFs and Networks.
Removing state `overridden` from this check
=> Config not required for state overridden

plugins/action/dcnm_image_upgrade.py
This is to update the timeout value in the ActionModule for dcnm_image_upgrade to 1800 seconds.
=> Update dcnm_image_upgrade action plugin timeout to 1800 seconds.

plugins/modules/dcnm_interface.py, tests/unit/modules/dcnm/fixtures/dcnm_intf_aa_fex_configs.json, tests/unit/modules/dcnm/fixtures/dcnm_intf_bunched_configs.json, tests/unit/modules/dcnm/fixtures/dcnm_intf_eth_configs.json, tests/unit/modules/dcnm/fixtures/dcnm_intf_lo_configs.json, tests/unit/modules/dcnm/fixtures/dcnm_intf_mixed_configs.json, tests/unit/modules/dcnm/fixtures/dcnm_intf_multi_configs.json, tests/unit/modules/dcnm/fixtures/dcnm_intf_multi_intf_configs.json, tests/unit/modules/dcnm/fixtures/dcnm_intf_pc_configs.json, tests/unit/modules/dcnm/fixtures/dcnm_intf_query_configs.json, tests/unit/modules/dcnm/fixtures/dcnm_intf_st_fex_configs.json, tests/unit/modules/dcnm/fixtures/dcnm_intf_subint_configs.json, tests/unit/modules/dcnm/fixtures/dcnm_intf_svi_configs.json, tests/unit/modules/dcnm/fixtures/dcnm_intf_vpc_configs.json
DCNM interface module has been updated to check for switch role and default ethernet interfaces to appropriate policy. for e.g. a switch with role as 'leaf' will be defaulted to policy trunk and switches with other roles will be defaulted to routed policy.
=> Code update to handle ethernet interface delete/default based on switch role

plugins/module_utils/fabric/replaced.py, tests/unit/modules/dcnm/dcnm_fabric/test_fabric_replaced_bulk.py
This fix addresses an issue Mike found with dcnm_fabric replaced state -> #305.
Changes include:
1. FabricReplacedCommon().update_replaced_payload()
If the playbook value for a parameter is None (which is the case when the playbook config does not contain the parameter), then the only thing we need to ensure is that the controller value is set to the default value.  If the default value is null, we change it to the empty string "" since NDFC throws a 500 error for null parameter values.
2. Update unit tests to reflect the above change.  The following test was modified.  Specifically two cases where the playbook parameter value is None (PARAM_8 and PARAM_15).
- test_fabric_replaced_bulk_00040
=> Fix for issue #305 (dcnm_fabric replaced state, implicit change handling)

plugins/modules/dcnm_links.py, tests/unit/modules/dcnm/fixtures/dcnm_links_payloads.json
Interface names can be specific to type of box used. In some cases a loopback interface may be like loopback100 and in some cases it will be like Loopback100. To make this transparent to the user, dcnm_links module has been updated to handle these cases.
=> Case agnostic checks for interface names in dcnm_links module

README.md, docs/cisco.dcnm.dcnm_interface_module.rst, plugins/modules/dcnm_interface.py, tests/integration/targets/dcnm_interface/tests/dcnm/dcnm_intf_override_specific_types.yaml, tests/unit/modules/dcnm/fixtures/dcnm_intf_common_configs.json, tests/unit/modules/dcnm/fixtures/dcnm_intf_have_all_payloads.json, tests/unit/modules/dcnm/fixtures/dcnm_intf_pc_payloads.json, tests/unit/modules/dcnm/test_dcnm_intf.py
By default interface module will delete/default all interface types during overridden/deleted states. The module has been updated to do the following:
- provide an optional list parameter in the playbook to include specific interface types
- if this list is empty, then the behaviour will be similar to what is already implemented i.e. all interface types will be handled during overridden and deleted states
- if this list includes specific interface types, then only those interface types will be handled during overridden and deleted states.
- this commit also fixes a couple of deploy issues during overridden/deleted states.
=> Fix to override only specified interface types instead of all types of interfaces

docs/cisco.dcnm.dcnm_policy_module.rst, plugins/modules/dcnm_policy.py
Fix typo in dcnm_policy module example where there is an incorrect switch list entry indentation.
=> Fix Typo in dcnm_policy Module Example

plugins/modules/dcnm_interface.py, tests/integration/targets/dcnm_interface/tests/dcnm/dcnm_pc_merge.yaml, tests/unit/modules/dcnm/fixtures/dcnm_intf_pc_configs.json, tests/unit/modules/dcnm/test_dcnm_intf.py
'allowed-vlans' parameter in interfaces with 'trunk' policy accepts only 'all', 'none' and vlan-ranges like 20-30 etc. There is no way for users to specify distinct individual vlans which are not contiguous. This code update handles these cases and enables users to input distinct individual vlans as part of 'allowed-vlans' parameter.
=> Fix for issue 229 to accept individual vlans in accepted-vlans parameter

plugins/modules/dcnm_vrf.py
Fixing an issue when running the module for a VRF that has been attached to a switch with loopback IPs. The current logic required both a v4 and v6 IP. But in reality you only need one or the other or both. Not require to need both.
=> Fix issue with VRF loopback attachment support

playbooks/roles/dcnm_network/ansible.cfg, playbooks/roles/dcnm_network/dcnm_hosts.yaml, playbooks/roles/dcnm_network/dcnm_tests.yaml, plugins/modules/dcnm_network.py
This fixes an intermittent issue deleting networks where key `is_deploy` is not defined.  This updates the code to use the safer `get` to access the dictionary key.
This also creates a test playbook directory to make it easier to run the `dcnm_network` integration tests.
=> dcnm_network: Fix key not found issue

plugins/module_utils/fabric/create.py, plugins/module_utils/fabric/fabric_types.py
Fixes an issue found by Alessandro De Prato where Ansible-created external fabrics (e.g. ISN) are displayed with incorrect Fabric Type column value in the NDFC GUI on page:
NDFC -> Manage -> Fabrics
For example, ISN fabric types are displayed with a column value of "Custom Fabric" but SHOULD be displayed with a column value of "Multi-Site External Network".
The reason is that the NDFC GUI adds the key `EXT_FABRIC_TYPE` to the payload with the value (in the case of ISN) of "Multi-Site External Network".
This only affects fabrics using the `External_Fabric` template.
I've tested to verify the fix and have tested to verify that the fix does not change behavior for non-External fabric types.
Have made the fix extensible, so that it can be applied to other fabric types that use the …
=> dcnm_fabric: Fix for issue 343

plugins/module_utils/network/dcnm/dcnm_vpc_pair_utils.py, plugins/modules/dcnm_vpc_pair.py, tests/unit/modules/dcnm/fixtures/dcnm_vpc_pair/dcnm_vpc_pair_response.json, tests/unit/modules/dcnm/test_dcnm_vpc_pair.py
This PR enabled the `useVirtualPeerlink` functionality for the `dcnm_vpc_pair` module
Resolves: https://github.com/CiscoDevNet/ansible-dcnm/issues/333
=> Enable useVirtualPeerlink in dcnm_vpc_pair module

plugins/modules/dcnm_interface.py
The `dcnm_interface` module currently has a check to see if devices are in a `manageable` state before attempting to create interfaces but this check is not needed and in fact breaks pre-provision workflows.
A device or switch state can be unmanageable for a variety of reasons but we should not be checking this state to use it for making configuration decisions.
=> Module: dcnm_interface - Remove Manageable Check for Interfaces

plugins/module_utils/network/dcnm/dcnm_vpc_pair_utils.py, plugins/modules/dcnm_vpc_pair.py
The `dcnm_vpc_pair` module currently has a check to see if devices are in a `manageable` state before attempting to put them into a vpc pair but this check is not needed and in fact breaks pre-provision workflows.
A device or switch state can be unmanageable for a variety of reasons but we should not be checking this state to use it for making configuration decisions.  A device that is in this state can still be configured as a vpc pair.
Removing this check but leaving the function in the library if we decide we need it down the road for different use cases.
=> Module: dcnm_vpc_pair - Remove Manageable Check for Devices

playbooks/roles/dcnm_image_policy/dcnm_tests.yaml, plugins/modules/dcnm_image_policy.py, tests/integration/targets/dcnm_image_policy/tests/dcnm_image_policy_overridden.yaml
The `dcnm_image_policy` module was not handling `overridden` state correctly.
It was correctly deleting image policies that were not in the playbook, but it was merging image policy configurations from the playbook with the image policy configurations on the controller.  It should have been REPLACING these configurations.
This PR addresses this by modifying the `Overridden()` class within `dcnm_image_policy.py` to call `Replaced().commit()` rather than `Merged().commit()`.
No changes are required for unit tests since the individual support modules are all doing what they are supposed to do.  The only issue here was that `dcnm_image_policy.py` (main module) was instantiating, and calling `commit()` on, the wrong class.
1. Updated `dcnm_image_policy` integration test.
a. For `overridden` …
=> dcnm_image_policy: fix for issue #347

plugins/module_utils/common/api/v1/configtemplate/rest/config/templates/templates.py, tests/unit/module_utils/common/api/test_api_v1_configtemplate_rest_config_templates.py
EpTemplate() used FabricTypes() to validate the template_name property against a list of supported fabric templates.  However, the intent of EpTemplate() is to retrieve other template types as well (interface, network, vrf, etc), so this validation isn't ideal in this larger context.
1. Removes this validation and the associated import and instantiation of FabricTypes().
2. Removes unit test that verified a ValueError is raised if template_name did not match one of the templates in FabricTypes().
=> EpTemplate() - remove template_name validation

plugins/modules/dcnm_interface.py
fix #358
Update if condition for sub_int to support two regex.
* EthernetX/yyy.zzz
* PortX.zzzzz
=> Add support for Port-Channel SubInterface

plugins/module_utils/common/controller_version.py, plugins/modules/dcnm_fabric.py, tests/unit/module_utils/common/fixtures/responses_ep_version.json, tests/unit/module_utils/common/test_controller_version.py
closes #360
The evaluation of controller features in dcnm_fabric.py was broken due to using the wrong key to access the features dictionary.  This PR fixes this, and also bypasses controller feature evaluation for ND 4.x.
1a. Fix dictionary access in `Merged.get_need()` and `Replaced.get_need()`
In the above methods, we were trying to retrieve the key `"fabric_type"` from the dict  `self.features`. But this dict is keyed on the fabric type (e.g. keys in this dict are `"ISN"`, `"VXLAN_EVPN"`, etc).
```python
self.features == {'IPFM': False, 'ISN': True, 'LAN_CLASSIC': True, 'VXLAN_EVPN': True, 'VXLAN_EVPN_MSD': True}
```
The fix is to remove the quotes around "fabric_type" -> fabric_type, which is a var containing the fabric type (`ISN`, `VXLAN_EVPN`, etc).
1b. Update feature evaluation …
=> dcnm_fabric: Fix evaluation of controller features

plugins/modules/dcnm_vrf.py
**Summary:**
This fixes two problems:
* There is a problem after creating a VRF when the `deploy` flag is set to `false`.  The first time the VRF will be created and remain in `pending` state in NDFC but the second time the playbook is run the VRF will be deployed even though the flag is still set to `false`.
* Fixes and idempotence issue with `bgpPasswordKeyType`.  Updated to use the correct default value.
**Sample Playbook:**
```yaml
- name: Manage VRFs
cisco.dcnm.dcnm_vrf:
fabric: nac-msd1
state: replaced
config:
- vrf_name: NaC-VRF01
vrf_id: 150001
vlan_id: 2001
vrf_intf_desc: Configured by Ansible NetAsCode
vrf_description: Configured by Ansible NetAsCode
vrf_int_mtu: 9216
loopback_route_tag: 12345
max_bgp_paths: 1
max_ibgp_paths: 2
ipv6_linklocal_enable: True
disable_rt_auto: False …
```
=> Prevent VRF deploy when user deploy flag is false

plugins/modules/dcnm_links.py
Update to fix https://github.com/CiscoDevNet/ansible-dcnm/issues/379
=> Update links module to fix error message when MACSEC status of have link doesn't exist

plugins/module_utils/fabric/fabric_details_v2.py, tests/unit/modules/dcnm/dcnm_fabric/test_fabric_details_by_name_v2.py
Adding a fabric property accessor that will be required by future commits for issue #352
=> dcnm_fabric: Add per_vrf_loopback_auto_provision accessor property.

plugins/modules/dcnm_vrf.py, tests/unit/modules/dcnm/test_dcnm_vrf.py
This is part 1 of multiple PRs to address issue #352.
Rather than attempting to address all the merge conflicts in PR #364, we're breaking that PR into multiple smaller PRs.  Eventually, PR #364 will be deleted.
The contents of this current PR do not affect functionality.  The changes consist of:
1. Update/Add logging messages to help understand the code flow.
2. Update some comments.
3. Update two unit tests due to difference is logged message.
=> dcnm_vrf: Update log messages and comments

plugins/modules/dcnm_inventory.py, tests/integration/targets/dcnm_fabric/tests/dcnm_fabric_replaced_save_deploy.yaml
#368 
**Testing Completed for Older NDFC version**
Issue:
Switch addition to inventory fails if Default credentials are not set in NDFC.
Solution:
- While discovering the switch adding the additional attribute discoveryCredForLan to discover using individual switch credentials.
- Also added dcnm_fabric IT issue fix as well.
=> Issue 368: #368

docs/cisco.dcnm.dcnm_interface_module.rst, plugins/action/tests/unit/ndfc_pc_members_validate.py, plugins/modules/dcnm_interface.py, tests/integration/targets/ndfc_interface/templates/ndfc_pc_create.j2, tests/integration/targets/ndfc_interface/templates/ndfc_pc_interfaces.j2, tests/integration/targets/ndfc_interface/templates/ndfc_pc_members.j2, tests/integration/targets/ndfc_interface/tests/ndfc_pc_members.yaml
Fix #350 
Add support Dot1q tunnel host
```
- name: Configure E1/12 interfaces
cisco.dcnm.dcnm_interface:
fabric: nac-ndfc3
state: replaced
config:
- name: eth1/14
type: eth
switch:
- 10.229.42.82
deploy: true
profile:
admin_state: true
mode: dot1q_tunnel_host
access_vlan: 46
description: "test dot1q tunnel host"
cmds: |
no lldp transmit
no lldp receive
no cdp enable
```
```
changed: [nac-ndfc3] => {
"changed": true,
"diff": [
{
"debugs": [],
"deferred": [],
"delete_deploy": [],
"deleted": [],
"deploy": [
{
"fabricName": "nac-ndfc3",
"ifName": "Ethernet1/14",
"serialNumber": "9XANRS8T83Y"
}
],
"merged": [],
"overridden": [],
"query": [],
"replaced": [
{
"interfaceType": "INTERFACE_ETHERNET",
"interfaces": [
{
"fabricName": "nac-ndfc3",
"ifName": "Ethernet1/14",
"interfaceType": …
```
=> Add support dot1q tunnel host on dcnm_interface

playbooks/roles/dcnm_policy/dcnm_hosts.yaml, playbooks/roles/dcnm_policy/dcnm_tests.yaml, plugins/modules/dcnm_policy.py, tests/integration/targets/dcnm_policy/tasks/dcnm.yaml, tests/integration/targets/dcnm_policy/tasks/main.yaml, tests/integration/targets/dcnm_policy/tests/dcnm/dcnm_policy_delete.yaml, tests/integration/targets/dcnm_policy/tests/dcnm/dcnm_policy_with_vars_merge.yaml
Fixes https://github.com/CiscoDevNet/ansible-dcnm/issues/398
**Summary of Updates:**
* Fixes problem where deleting a policy with `deploy: false` marks the policy as deleted but does not delete the configuration from the switch when a deploy is executed (global or switch level)
* Adds a test playbook to easily run the dcnm_policy integration tests and fixes a few issues with the tests
=> Fix policy delete for freeform deploy false

docs/cisco.dcnm.dcnm_interface_module.rst, plugins/modules/dcnm_interface.py
add code for merge and delete breakout interface
```
- name: Configure breakout interface
tags: cr_breakout
cisco.dcnm.dcnm_interface:
fabric: "{{ fab }}"
state: merged
config:
- name: ethernet1/100
type: breakout
switch:
- "{{ switch }}"
deploy: true
profile:
map: 10g-4x
- name: ethernet1/101
type: breakout
switch:
- "{{ switch }}"
deploy: true
profile:
map: 10g-4x
- name: ethernet1/102
type: breakout
switch:
- "{{ switch }}"
deploy: true
profile:
map: 10g-4x
- name: ethernet1/102/1
type: eth
switch:
- "{{ switch }}"
deploy: true
profile:
mode: access
description: "TEST breakout merged e1/102/1"
- name: ethernet1/102/4
type: eth
switch:
- "{{ switch }}"
deploy: true
profile:
mode: access
description: "TEST breakout merged e1/102/4"
- name: Configure breakout interface
tags: rm_breakout …
```
=> Add breakout interface

plugins/modules/dcnm_interface.py
Update the key list to remove any keys that are not present in the 'have' list. This occurs when we retrieve the interface for the first time, as not all keys are initially available.
=> Fix the key list to be remove

plugins/modules/dcnm_network.py
Issue:
https://github.com/CiscoDevNet/ansible-dcnm/issues/80
Code Changes Description:
From the ports parameter in the DCNM Network Class, remove "required" constraint and add default value.
=> Fix for Issue #80 "dcnm_network requires ports attribute when attaching to switch"

plugins/modules/dcnm_inventory.py
**Summary:**
The dcnm_inventory module does not currently handle cases where a device is unreachable.
This could be for any of the following reasons:
* Device has been pre-provisioned
* Device is in POAP mode
* Device is not reachable due to some other network issue
**Adding devices to the fabric:**
When a device needs to be added to the fabric but is unreachable the following error message is generated and execution stops which is appropriate.
```python
msg = "Switch with IP {0} is not reachable or is not a valid IP".format(want_c["seedIP"])
```
If a device has already been added to the fabric but is currently unreachable it should still be managed because it's already part of the fabric.
This update makes an additional check to see if the device has already been added but is not …
=> dcnm_inventory: Device not reachable fixes

.github/workflows/main.yml
Pydantic and deepdiff was being installed when running UTs. These are unneeded.
=> removed pydantic and deepdiff as it is not needed in unit tests

tests/integration/targets/dcnm_network/tasks/main.yaml, tests/integration/targets/dcnm_network/templates/self-contained-tests/double_net_dhcp_changed_conf.j2, tests/integration/targets/dcnm_network/templates/self-contained-tests/double_net_dhcp_conf.j2, tests/integration/targets/dcnm_network/templates/self-contained-tests/double_net_mcast_changed_conf.j2, tests/integration/targets/dcnm_network/templates/self-contained-tests/double_net_mcast_conf.j2, tests/integration/targets/dcnm_network/templates/self-contained-tests/net1_changed_conf.j2, tests/integration/targets/dcnm_network/templates/self-contained-tests/net1_conf.j2, tests/integration/targets/dcnm_network/templates/self-contained-tests/net1_dhcp_changed_conf.j2, tests/integration/targets/dcnm_network/templates/self-contained-tests/net1_mcast_changed_conf.j2, tests/integration/targets/dcnm_network/templates/self-contained-tests/net1_mcast_conf.j2, tests/integration/targets/dcnm_network/templates/self-contained-tests/net2_conf.j2, tests/integration/targets/dcnm_network/tests/dcnm/merged.yaml
dcnm_network is updated by #427 which makes ports an optional parameter with a default value.
A test case which still expects ports to be mandatory is removed and backward compatibility is removed as it is no longer needed
=> Updated IT: dcnm_network to be in parity with new changes to dcnm_network 

plugins/modules/dcnm_vrf.py
Adding L3VNI w/o VLAN option support for dcnm_vrf module, requested through #337. 
Using "l3vni_wo_vlan" as the config parameter, which takes in "true" or "false" from the user end, to enable or disable the feature. By default, it is disabled (false).
JSON VRF Template Payload parameter, "enableL3VniNoVlan" is used to pass on the information to the NDFC.
=> dcnm_vrf: Add L3VNI w/o VLAN support, #337

plugins/module_utils/common/controller_version.py, tests/unit/module_utils/common/fixtures/responses_ep_version.json, tests/unit/module_utils/common/test_controller_version.py
Proposed fix for issue  #469
This PR makes the following changes to controller_version.py (ControllerVersion) and its unit tests.
1. Add a check in `ControllerVersion.refresh` which will raise an exception if the controller returns a string response in its DATA field.
2. Adds new fixtures for ND 4.1 version formats.
3. Updates unit tests for ControllerVersion to expect ValueError if:
- The controller response does not contain the version parameter
- The controller response does not contain the mode parameter
The modules in this collection that use ControllerVersion and would be impacted by this issue are:
- dcnm_fabric
- dcnm_image_upgrade
Below is Claude's summary of the fix after a few iterations (detailed in the individual commits).
⏺ Perfect! The logic works correctly. The validation …
=> dcnm_fabric: Proposed fix for issue #469

plugins/module_utils/common/conversion.py, tests/unit/module_utils/common/test_conversion_utils.py, tests/unit/modules/dcnm/dcnm_fabric/test_fabric_create.py, tests/unit/modules/dcnm/dcnm_fabric/test_fabric_create_bulk.py
The `ConversionUtils` class lacked associated unit tests.  Adding them now.
- `translate_mac_address` could throw an unintended TypeError with integer input since the re.sub() was trying to alter the passed `mac_addr`, which could potentially be an `int`.  Fixed by casting `mac_addr` to `str` within the `re.sub()`.
- `translate_mac_address` was returning the altered MAC address in its ValueError which could be confusing to the end user.  Fixed by copying the original `mac_addr` and using the copy in the ValueError.
Two fabric unit tests started failing after the above changes now that we are using the original MAC address in the ValueError.  Fixed the asserts in these to expect the original MAC address.
=> ConversionUtils() unit tests and hardening

plugins/module_utils/fabric/verify_playbook_params.py
The issue was in the parameter validation logic in **verify_playbook_params.py**
When comparing parameter values during validation, the code was inconsistently processing values through the conversion utilities:
- Playbook values (like RP_COUNT: 4) were processed through **make_boolean()**
- Controller values were processed through **make_boolean()**
- Default values from templates were not processed through conversions at all
- Rule values from templates were not processed through conversions
- This caused type mismatches during comparison where integer 4 from the playbook wouldn't properly compare with expected integer values in validation rules.
I modified the following methods in **verify_playbook_params.py** to ensure all values are consistently processed
=> dcnm_fabric: Fix for #441

plugins/modules/dcnm_inventory.py
Resolves https://github.com/CiscoDevNet/ansible-dcnm/issues/389
Had to change nonMdsModel to Model and when switching roles, now we use serial number instead of switchDbID. 
Old endpoints
--
GET /appcenter/cisco/ndfc/api/about/version
GET /appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{fabricName}/inventory
GET /appcenter/cisco/ndfc/api/v1/lan-fabric/rest/lanConfig/getLanSwitchCredentials
PUT /fm/fmrest/topology/role/{switchDbId}?newRole=leaf
New endpoints
--
GET /appcenter/cisco/ndfc/api/v1/fm/about/version
GET /appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{fabricName}}/inventory/switchesByFabric
GET /appcenter/cisco/ndfc/api/v1/lan-fabric/rest/lanConfig/getLanSwitchCredentialsWithType
POST /appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/switches/roles
=> changed unpublished endpoints to published ones

plugins/modules/dcnm_vrf.py
```yaml
- name: Configure VRFs
cisco.dcnm.dcnm_vrf:
fabric: nac-msd-fabric1
state: deleted
config:
- vrf_name: NetAsCodeVrf1
vrf_id: 150001
vlan_id: 2001
vrf_intf_desc: Configured by Ansible NetAsCode
vrf_description: Configured by Ansible NetAsCode
vrf_int_mtu: 9216
loopback_route_tag: 12345
max_bgp_paths: 1
max_ibgp_paths: 2
ipv6_linklocal_enable: True
adv_host_routes: False
adv_default_routes: True
static_default_route: True
disable_rt_auto: False
netflow_enable: False
no_rp: False
trm_enable: False
redist_direct_rmap: FABRIC-RMAP-REDIST-SUBNET
attach:
- ip_address: 10.15.34.13  ## Leaf1
- ip_address: 10.15.34.14  ## Leaf2
- ip_address: 10.15.34.15  ## Leaf3
- ip_address: 10.15.34.16  ## Leaf4
deploy: false
```
* Run the playbook above
* Initially the VRF will be created and attached …
=> VRFs should never deploy when deploy flag is False

docs/cisco.dcnm.dcnm_rest_module.rst, plugins/httpapi/dcnm.py, plugins/module_utils/network/dcnm/dcnm.py, plugins/modules/dcnm_rest.py
Issue:
https://github.com/CiscoDevNet/ansible-dcnm/issues/366
Fix:
Add support for API requests with body-data encoding type 'x-www-form-urlencoded', through attribute "urlencoded_data" in the dcnm_rest module. 
Example:
```yaml
tasks:
- name: Save Robot Credentials
cisco.dcnm.dcnm_rest:
method: POST
path: 'https://192.168.1.2/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/lanConfig/saveRobotCredentials'
urlencoded_data: '{"password": "password","confirmPassword": "password","isRobot":true,"username": "admin"}'
```
=> DCNM_REST: Adding support for Encoding Type 'x-www-form-urlencoded'

plugins/httpapi/dcnm.py, tests/unit/plugins/httpapi/test_dcnm.py
We discovered a problem where onemanage API's are resulting in truncated output for various `GET` calls.  The same APIs work fine with postman or curl which led to a deeper investigation into our httpapi plugin.  Adding the new header appears to solve "chunking" or truncating issue.
=> Add Transfer-Encoding chunked header
